server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: "user-1"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer



topic:
  info-notification: info-notification
  registration-notification: registration-notification